[project]
name = "notebooks"
version = "0.1.0"
description = "Notebooks that cover AI/ML/DS"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.0",
]
